/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export type Partner = {
  name?: string;
  current?: boolean;
  id?: string;
}[];
export type Children = {
  name?: string;
  id?: string;
}[];

export interface Config {
  collections: {
    members: Member;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Member {
  id: string;
  prefix?: 'Mr' | 'Master' | 'Miss' | 'Mrs' | 'Ms' | 'Mx';
  firstName: string;
  middleName?: string;
  lastName: string;
  suffix?: string;
  preferredName?: string;
  nickname?: string;
  fullNamePreferred?: string;
  location?: string;
  class?: number;
  address?: string;
  city?: string;
  state?:
    | 'AL'
    | 'AK'
    | 'AZ'
    | 'AR'
    | 'CA'
    | 'CO'
    | 'CT'
    | 'DE'
    | 'FL'
    | 'GA'
    | 'HI'
    | 'ID'
    | 'IL'
    | 'IN'
    | 'IA'
    | 'KS'
    | 'KY'
    | 'LA'
    | 'ME'
    | 'MD'
    | 'MA'
    | 'MI'
    | 'MN'
    | 'MS'
    | 'MO'
    | 'MT'
    | 'NE'
    | 'NV'
    | 'NH'
    | 'NJ'
    | 'NM'
    | 'NY'
    | 'NC'
    | 'ND'
    | 'OH'
    | 'OK'
    | 'OR'
    | 'PA'
    | 'RI'
    | 'SC'
    | 'SD'
    | 'TN'
    | 'TX'
    | 'UT'
    | 'VT'
    | 'VA'
    | 'WA'
    | 'WV'
    | 'WI'
    | 'WY';
  zip?: string;
  country?: string;
  fullAddress?: string;
  email?: string;
  altEmail?: string;
  phone?: string;
  altPhone?: string;
  bigBrother?: string | Member;
  littleBrothers?: string[] | Member[];
  major?: string;
  occupation?: Work;
  lost?: boolean;
  dead?: boolean;
  deathDate?: string;
  obitUrl?: string;
  hrog?: boolean;
  hrogDate?: string;
  national?: {
    nhqId?: string;
    initiation?: string;
    pin?: string;
  };
  notes?: string;
  slug?: string;
  user?: string | User;
  spouse?: Partner;
  children?: Children;
  updatedAt: string;
  createdAt: string;
}
export interface Work {
  title?: string;
  employer?: string;
  usService?: string;
}
export interface User {
  id: string;
  name?: string;
  roles?: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string;
  batch?: number;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes {
    collections: {
      'members': Member
      'users': User
      'payload-preferences': PayloadPreference
      'payload-migrations': PayloadMigration
    }

  }
}